// <auto-generated />
using Brands.DataLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Brands.DataLayer.Migrations
{
    [DbContext(typeof(BrandsContext))]
    [Migration("20230113053052_changePicToNullableField")]
    partial class changePicToNullableField
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Brands.DataLayer.Entities.Brands", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrandPicture")
                        .HasColumnName("Picture Name of Brand")
                        .HasMaxLength(200);

                    b.Property<string>("EnglishBrandName")
                        .IsRequired()
                        .HasColumnName("English Brand Name")
                        .HasMaxLength(100);

                    b.Property<bool>("IsDelete");

                    b.Property<string>("PersianBrandName")
                        .IsRequired()
                        .HasColumnName("Persian Brand Name")
                        .HasMaxLength(75);

                    b.Property<int>("UserId");

                    b.HasKey("BrandId");

                    b.HasIndex("UserId");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("Brands.DataLayer.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnName("Password")
                        .HasMaxLength(200);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnName("User Name")
                        .HasMaxLength(200);

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Brands.DataLayer.Entities.Brands", b =>
                {
                    b.HasOne("Brands.DataLayer.Entities.User", "Users")
                        .WithMany("Brands")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
